### ISSUE TITLE
django.db.utils.InternalError: (1366, "Incorrect string value: '\\xE6\\x8E\\xA5\\xE5\\x8F\\xA3...' for column 'name' at row 1")

### ISSUE THREAD

**Issue by xiaoqi7s** [githublitao/api_automation_test#29]
当我执行命令python3 manage.py migrate时报错如下：
[root@sur api_automation_test-master]# python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, api_test, auth, authtoken, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying api_test.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying sessions.0001_initial... OK
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 893, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1103, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1396, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1059, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1366, "Incorrect string value: '\\xE6\\x8E\\xA5\\xE5\\x8F\\xA3...' for column 'name' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 223, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "/usr/local/lib/python3.6/site-packages/django/core/management/sql.py", line 51, in emit_post_migrate_signal
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 178, in send
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/management/__init__.py", line 79, in create_permissions
    Permission.objects.using(using).bulk_create(perms)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 466, in bulk_create
    ids = self._batched_insert(objs_without_pk, fields, batch_size)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1148, in _batched_insert
    self._insert(item, fields=fields, using=self.db)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1125, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1281, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 893, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1103, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1396, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1059, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1366, "Incorrect string value: '\\xE6\\x8E\\xA5\\xE5\\x8F\\xA3...' for column 'name' at row 1")

**Comment by githublitao** [comment]
重新配置环境

**Comment by xiaoqi7s** [comment]
前面的问题是由于数据库不是utf8导致，重新创建之后就行了。但是又遇到以下的问题：
node -v v10.14.2
npm -v 6.5.0
---当执行npm install时有下面的警告，
[root@sur frontend]# npm install
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.4.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@3.1.14 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 14739 packages in 12.13s
found 0 vulnerabilities

---但是在执行npm run build时有以下报错
[root@sur frontend]# npm run build

> frontend@1.0.0 build /root/api_automation_test-master/frontend
> node build/build.js

Hash: db370c1e716c33024c0a
Version: webpack 3.12.0
Time: 62070ms
                                     Asset       Size  Chunks                    Chunk Names
      static/js/15.72042bfb85e38ca4b537.js     117 kB      15  [emitted]
          static/img/userphoto.6d73d26.jpg    13.5 kB          [emitted]
       static/js/0.c23a9b08b78da5a41774.js     797 kB       0  [emitted]  [big]
       static/js/1.e2159d75c7da8a3690cf.js     363 kB       1  [emitted]  [big]
       static/js/2.e4f69fc21862f5a9a111.js     371 kB       2  [emitted]  [big]
       static/js/3.3e965557da93301d6eed.js     362 kB       3  [emitted]  [big]
       static/js/4.69c2d6557dca28fc99d0.js     166 kB       4  [emitted]
       static/js/5.1554bf281cf7a20e107c.js     150 kB       5  [emitted]
       static/js/6.7156b06f30960d00fa4a.js    61.2 kB       6  [emitted]
       static/js/7.86b7f44acbd3654fcff8.js     143 kB       7  [emitted]
       static/js/8.3b45458d93faab211b66.js    38.9 kB       8  [emitted]
       static/js/9.34b1aa6f501b91c71fa1.js    38.1 kB       9  [emitted]
      static/js/10.0ba6d3b749121db3cbcc.js    47.3 kB      10  [emitted]
      static/js/11.85e41efe5d1570a9894c.js     128 kB      11  [emitted]
      static/js/12.9fb64413b6aed9675eba.js     127 kB      12  [emitted]
      static/js/13.82d71092c775f4075f46.js     113 kB      13  [emitted]
      static/js/14.09affccb830bb2227f9d.js     116 kB      14  [emitted]
            static/img/page1_3.17bc0b8.jpg    41.4 kB          [emitted]
      static/js/16.9d4bf62e9deca9f57efe.js     119 kB      16  [emitted]
      static/js/17.c578e9b6f2ce3b82d3f5.js     123 kB      17  [emitted]
      static/js/18.902e7bae99ac78449016.js     114 kB      18  [emitted]
      static/js/19.2b0c8700f81a6620861e.js     109 kB      19  [emitted]
      static/js/20.79f1395f3f2fcbf077ea.js    34.7 kB      20  [emitted]
      static/js/21.0aaf2f232546c052a897.js    27.7 kB      21  [emitted]
      static/js/22.54b209d80f4c0bb9a2f2.js    26.7 kB      22  [emitted]
      static/js/23.a86c39d81a5be78ad52e.js    22.1 kB      23  [emitted]
      static/js/24.a4465e758b3d3a4c76a3.js    5.05 kB      24  [emitted]
      static/js/25.a53628facb71524a089d.js    5.03 kB      25  [emitted]
      static/js/26.c0ecf8fb08d8362a82f7.js    2.04 kB      26  [emitted]
      static/js/27.5fdd4439965cf7828b1c.js  328 bytes      27  [emitted]
     static/js/app.fe6161da0c26889deb85.js    8.76 kB      28  [emitted]         app
  static/js/vendor.4322a0d4d2a17bf2349d.js    3.35 kB      29  [emitted]         vendor
static/js/manifest.4d44fab22d5c4dc45172.js     2.1 kB      30  [emitted]         manifest
                                index.html    1.33 kB          [emitted]

ERROR in ./node_modules/css-loader?{"minimize":true,"sourceMap":false}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-0d1ed23c","scoped":true,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/views/project/automation/CaseListGroup.vue
Module build failed: Error: ENOENT: no such file or directory, scandir '/root/api_automation_test-master/frontend/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:786:3)
    at Object.getInstalledBinaries (/root/api_automation_test-master/frontend/node_modules/node-sass/lib/extensions.js:130:13)
    at foundBinariesList (/root/api_automation_test-master/frontend/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/root/api_automation_test-master/frontend/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/root/api_automation_test-master/frontend/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/root/api_automation_test-master/frontend/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/root/api_automation_test-master/frontend/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (/root/api_automation_test-master/frontend/node_modules/sass-loader/lib/loader.js:46:72)
 @ ./node_modules/extract-text-webpack-plugin/dist/loader.js?{"omit":1,"remove":true}!./node_modules/vue-style-loader!./node_modules/css-loader?{"minimize":true,"sourceMap":false}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-0d1ed23c","scoped":true,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/views/project/automation/CaseListGroup.vue 4:14-424
 @ ./src/views/project/automation/CaseListGroup.vue
 @ ./src/routes.js
 @ ./src/main.js

**Comment by xiaoqi7s** [comment]
[root@sur frontend]# npm run build

> frontend@1.0.0 build /root/api_automation_test-master/frontend
> node build/build.js

⠼ building for production...
⠼ building for production...已杀死

真的是各种问题……
