### ISSUE TITLE
我在frontend目录下执行npm run build报错

### ISSUE THREAD

**Issue by lwb2001258** [githublitao/api_automation_test#34]
我已经安装了npm,vue，不知道为什么，报错信息如下，不知道为什么了，谢谢！

> frontend@1.0.0 build F:\appiumforone\LucePindian\api_automation_test-master\api_automation_test-master\frontend
> node build/build.js

module.js:549
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\appiumforone\LucePindian\api_automation_test-master\api_automation_test-master\frontend\build\check-versions.js:1:75)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-03-11T06_15_52_958Z-debug.log

**Comment by yuanzhen141113** [comment]
me too

**Comment by githublitao** [comment]
这个问题，百度就能解决，缺失包而已
