### ISSUE TITLE
pip install -r requirements.txt  时 python-docx uWSGI 模块安装失败

### ISSUE THREAD

**Issue by god-pane** [githublitao/api_automation_test#88]
D:\Python_project\api_automation_test_django>pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: certifi==2018.1.18 in c:\python37\lib\site-packages (from -r requirements.txt (line 1)) (2018.1.18)
Requirement already satisfied: Django==2.0.2 in c:\python37\lib\site-packages (from -r requirements.txt (line 2)) (2.0.2)
Requirement already satisfied: django-cors-headers==2.1.0 in c:\python37\lib\site-packages (from -r requirements.txt (line 3)) (2.1.0)
Requirement already satisfied: djangorestframework==3.7.7 in c:\python37\lib\site-packages (from -r requirements.txt (line 4)) (3.7.7)
Requirement already satisfied: idna==2.6 in c:\python37\lib\site-packages (from -r requirements.txt (line 5)) (2.6)
Requirement already satisfied: pytz==2017.3 in c:\python37\lib\site-packages (from -r requirements.txt (line 6)) (2017.3)
Requirement already satisfied: requests==2.18.4 in c:\python37\lib\site-packages (from -r requirements.txt (line 7)) (2.18.4)
Requirement already satisfied: django-rest-swagger==2.1.2 in c:\python37\lib\site-packages (from -r requirements.txt (line 8)) (2.1.2)
ERROR: Exception:
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in _main
    status = self.run(options, args)
  File "c:\python37\lib\site-packages\pip\_internal\cli\req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "c:\python37\lib\site-packages\pip\_internal\commands\install.py", line 319, in run
    reqs, check_supported_wheels=not options.target_dir
  File "c:\python37\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 128, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "c:\python37\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "c:\python37\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "c:\python37\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _merge_into_criterion
    if not criterion.candidates:
  File "c:\python37\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 139, in __bool__
    return bool(self._sequence)
  File "c:\python37\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in __bool__
    return any(self)
  File "c:\python37\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 129, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "c:\python37\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 30, in _iter_built
    for version, func in infos:
  File "c:\python37\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 272, in iter_index_candidate_infos
    hashes=hashes,
  File "c:\python37\lib\site-packages\pip\_internal\index\package_finder.py", line 879, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "c:\python37\lib\site-packages\pip\_internal\index\package_finder.py", line 824, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "c:\python37\lib\site-packages\pip\_internal\index\sources.py", line 134, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "c:\python37\lib\site-packages\pip\_internal\index\package_finder.py", line 783, in process_project_url
    html_page = self._link_collector.fetch_page(project_url)
  File "c:\python37\lib\site-packages\pip\_internal\index\collector.py", line 512, in fetch_page
    return _get_html_page(location, session=self.session)
  File "c:\python37\lib\site-packages\pip\_internal\index\collector.py", line 422, in _get_html_page
    resp = _get_html_response(url, session=session)
  File "c:\python37\lib\site-packages\pip\_internal\index\collector.py", line 137, in _get_html_response
    "Cache-Control": "max-age=0",
  File "c:\python37\lib\site-packages\pip\_vendor\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "c:\python37\lib\site-packages\pip\_internal\network\session.py", line 449, in request
    return super().request(method, url, *args, **kwargs)
  File "c:\python37\lib\site-packages\pip\_vendor\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python37\lib\site-packages\pip\_vendor\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "c:\python37\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\python37\lib\site-packages\pip\_vendor\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\python37\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "c:\python37\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "c:\python37\lib\site-packages\pip\_vendor\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "c:\python37\lib\site-packages\pip\_vendor\urllib3\connection.py", line 506, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "c:\python37\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "c:\python37\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "c:\python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "c:\python37\lib\ssl.py", line 810, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

麻烦给看下，是否有其他模块的版本号不对呀

**Comment by JiinJie** [comment]
同问，我也是在build uwsgui这边报错

**Comment by 947612227** [comment]
我解决了
python3  -m pip install --upgrade pip #twine 3.4.1 requires requests>=2.20, but you have requests 2.18.4 which is incompatible.
pip3 install requests==2.20
pip3 install https://github.com/darklow/django-suit/tarball/v2

**Comment by snailComing** [comment]
> 我解决了 python3 -m pip install --upgrade pip #twine 3.4.1 requires requests>=2.20, but you have requests 2.18.4 which is incompatible. pip3 install requests==2.20 pip3 install https://github.com/darklow/django-suit/tarball/v2

楼主是windows系统解决了吗？

**Comment by snailComing** [comment]
Collecting python-crontab==2.2.8
     command: 'D:\ProgramData\Anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\31832\\AppData\\Local\\Temp\\pip-install-ld9lvd1z\\uwsgi_cdcb1fd06ddb
4f4ba87da6276e90bc64\\setup.py'"'"'; __file__='"'"'C:\\Users\\31832\\AppData\\Local\\Temp\\pip-install-ld9lvd1z\\uwsgi_cdcb1fd06ddb4f4ba87da6276e90bc64\\setup.py'"'"';f = getattr(tokenize, '"'"'ope
n'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(co
de, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\31832\AppData\Local\Temp\pip-pip-egg-info-9_ygvhwb'
         cwd: C:\Users\31832\AppData\Local\Temp\pip-install-ld9lvd1z\uwsgi_cdcb1fd06ddb4f4ba87da6276e90bc64\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\31832\AppData\Local\Temp\pip-install-ld9lvd1z\uwsgi_cdcb1fd06ddb4f4ba87da6276e90bc64\setup.py", line 3, in <module>
        import uwsgiconfig as uc
      File "C:\Users\31832\AppData\Local\Temp\pip-install-ld9lvd1z\uwsgi_cdcb1fd06ddb4f4ba87da6276e90bc64\uwsgiconfig.py", line 8, in <module>
        uwsgi_os = os.uname()[0]
    AttributeError: module 'os' has no attribute 'uname'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e7/1e/3dcca007f974fe4eb369bf1b8629d5e342bb3055e2001b2e5340aaefae7a/uwsgi-2.0.18.tar.gz#sha256=4972ac538800fb2d421027f49b4a1869b6604883950
7ccf0aa2fda792d99f583 (from https://pypi.org/simple/uwsgi/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement uWSGI==2.0.18 (from versions: 1.4.9, 1.4.10, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.9.10, 1.9.11, 1.9.1
2, 1.9.13, 1.9.14, 1.9.15, 1.9.16, 1.9.17, 1.9.17.1, 1.9.18, 1.9.18.1, 1.9.18.2, 1.9.19, 1.9.20, 1.9.21, 1.9.21.1, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.5.1, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.1
0, 2.0.11, 2.0.11.1, 2.0.11.2, 2.0.12, 2.0.13, 2.0.13.1, 2.0.14, 2.0.15, 2.0.16, 2.0.17, 2.0.17.1, 2.0.18, 2.0.19, 2.0.19.1, 2.0.20)
ERROR: No matching distribution found for uWSGI==2.0.18
有谁解决了吗？
